# 项目相关配置
wjzc:
  # 名称
  name: 五减政策
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/wjzc/uploadPath，Linux配置 /home/wjzc/uploadPath）
  profile: D:/wjzc/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 日志配置
logging:
  level:
    com.wjzc: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: test
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: B0stech123!@#
  # 令牌有效期（默认30分钟）
  expireTime: 30


mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #field-strategy: NOT_NULL # 3.1.2 使用insertStrategy、updateStrategy、selectStrategy替代，默认值均为 NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
    #是否缓存 Sql 解析，默认不缓存;使用SqlParser注解，必须开启（3.1.1开始不再需要这一步）
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  typeEnumsPackage: com.wjzc.**.enums

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: wjzc
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.wjzc.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_